-- DropForeignKey
ALTER TABLE `event` DROP FOREIGN KEY `Event_userId_fkey`;

-- AlterTable
ALTER TABLE `event` MODIFY `header` VARCHAR(191) NULL,
    MODIFY `detail` VARCHAR(191) NULL,
    MODIFY `userId` INTEGER NULL,
    MODIFY `createAt` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    MODIFY `updateAt` TIMESTAMP(0) NOT NULL;

-- AlterTable
ALTER TABLE `field` MODIFY `createAt` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    MODIFY `updateAt` TIMESTAMP(0) NOT NULL;

-- AlterTable
ALTER TABLE `task` MODIFY `createAt` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    MODIFY `updateAt` TIMESTAMP(0) NOT NULL;

-- AlterTable
ALTER TABLE `user` MODIFY `createAt` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    MODIFY `updateAt` TIMESTAMP(0) NOT NULL;

-- AlterTable
ALTER TABLE `watering` MODIFY `createAt` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    MODIFY `updateAt` TIMESTAMP(0) NOT NULL;

-- AddForeignKey
ALTER TABLE `Event` ADD CONSTRAINT `Event_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
